version: '3'

# Docs: https://docs.stardog.com/get-started/install-stardog/docker
# Issue posted: https://community.stardog.com/t/deploy-stardog-behind-a-reverse-nginx-proxy/3126

services:

  # Deploy a Stardog server
  stardog:
    image: stardog/stardog:8.2.2-java11-preview
    restart: unless-stopped
    volumes:
      - /data/stardog:/var/opt/stardog
      - ./drivers:/var/opt/stardog-ext
    ports:
      - 5820:5820
    environment:
      - "STARDOG_SERVER_JAVA_ARGS=-Xmx8g -Xms8g -XX:MaxDirectMemorySize=12g"
      - "JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true"
      - STARDOG_EXT=/var/opt/stardog-ext
      - LETSENCRYPT_HOST=stardog.137.120.31.102.nip.io
      - VIRTUAL_HOST=stardog.137.120.31.102.nip.io
      - VIRTUAL_PORT=5820
    # Make sure system metadata and databases are properly upgraded:
    # command: --upgrade

  postgres-patients-cohort1:
    image: postgres
    # image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD:-passwordtochange}
      # - POSTGRES_DB=heart_failure_db
    # ports:
    #   - 5432:5432
    volumes:
      # Copy the sql script to create tables
      - ./sql-vkg/patients_cohort1_postgres.sql:/docker-entrypoint-initdb.d/patients_cohort1_postgres.sql
      - ./sql-vkg/PATIENTS_cohort1.csv:/data/PATIENTS_cohort1.csv
      # - ./data/postgres:/var/lib/postgresql/data

  postgres-patients-cohort2:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD:-passwordtochange}
    # ports:
    #   - 5432:5432
    volumes:
      - ./sql-vkg/patients_cohort2_postgres.sql:/docker-entrypoint-initdb.d/patients_cohort2_postgres.sql
      - ./sql-vkg/PATIENTS_cohort2.csv:/data/PATIENTS_cohort2.csv


  mariadb-patients-cohort3:
    restart: unless-stopped
    image: mariadb
    # ports:
    #   - 3306:3306
    volumes:
      - ./sql-vkg/patients_cohort3_mariadb.sql:/docker-entrypoint-initdb.d/patients_cohort3_mariadb.sql
      - ./sql-vkg/PATIENTS_cohort3.csv:/data/PATIENTS_cohort3.csv
      # - ./data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${PASSWORD-passwordtochange}
      MARIADB_USER: user
    # command: --max-allowed-packet=16M --local_infile=1


  # ontop:
  #   image: ontop/ontop
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/data
  #     # - ./drill-override.conf:/opt/drill/conf/drill-override.conf
  #   # ports:
  #   #   - 8047:8047 # web and REST
  #   #   - 31010:31010 # JDBC
  #   stdin_open: true
  #   environment:
  #     - ONTOP_MAPPING_FILE=/data/ontop.rml.ttl
  #     - ONTOP_ONTOLOGY_FILE=/data/ontop.rdf
  #     - ONTOP_DB_USER=postgres
  #     - ONTOP_DB_PASSWORD=${PASSWORD:-passwordtochange}
  #     # - ONTOP_PROPERTIES_FILE=/data/ontop.properties
  #     # https://ontop-vkg.org/guide/advanced/configuration.html



  # heart-failure-drill:
  #   image: apache/drill
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/data
  #     # - ./drill-override.conf:/opt/drill/conf/drill-override.conf
  #   # ports:
  #   #   - 8047:8047 # web and REST
  #   #   - 31010:31010 # JDBC
  #   stdin_open: true
  #   environment:
  #     - DRILLBIT_MAX_PROC_MEM=8G
  #     - DRILL_HEAP=4G
  #     - DRILL_MAX_DIRECT_MEMORY=8G
  #     - DRILLBIT_CODE_CACHE_SIZE=1G


  # stardog-studio:
  #   image: stardog/stardog-studio:current
  #   container_name: stardog-studio
  #   restart: unless-stopped
  #   environment:
  #     - LETSENCRYPT_HOST=studio.stardog.137.120.31.102.nip.io
  #     - VIRTUAL_HOST=studio.stardog.137.120.31.102.nip.io
  #     - VIRTUAL_PORT=8080
  #   network_mode: bridge
