version: '3'

services:
  
  nifi-stardog:
    build: .
    # image: apache/nifi
    restart: unless-stopped
    volumes:
      - ./nifi-example:/data

      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/logs:/opt/nifi/nifi-current/logs

    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTPS_PORT=8080
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=${PASSWORD:-password1234}
      # 12 char min

      # - NIFI_WEB_HTTP_PORT=8080 
      # HTTP does not work because nifi cant disable auth by default,
      # and block auth if HTTP enabled. True geniuses at work

      # - VIRTUAL_PORT=8080
      # - LETSENCRYPT_HOST=nifi.stardog.137.120.31.102.nip.io
      # - VIRTUAL_HOST=nifi.stardog.137.120.31.102.nip.io
